apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-api-config
data:
  CONNECTION_STRINGS: "User ID=user01;Password=Abcd@1234;Host=postgres-service;Port=5432;Database=billingmanagerdb;Pooling=true;"
  REDIS_HOST: "redis-service:6379,password=Abcd@1234"
  SEQ_SERVER_URL: "http://seq-service:80/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing-api
  template:
    metadata:
      labels:
        app: billing-api
    spec:
      containers:
      - name: billing-api
        image: ellisonguimaraes/billing-api:v2
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: billing-api-config
              key: CONNECTION_STRINGS
        - name: RedisSettings__Host
          valueFrom:
            configMapKeyRef:
              name: billing-api-config
              key: REDIS_HOST
        - name: Serilog__WriteTo__0__Args__serverUrl
          valueFrom:
            configMapKeyRef:
              name: billing-api-config
              key: SEQ_SERVER_URL
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 2
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: billing-api-service
spec:
  selector:
    app: billing-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
