//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManager.Domain.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BillingManager.Domain.Resources.ErrorsResource", typeof(ErrorsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NOT_FOUND_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("NOT_FOUND_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string NOT_FOUND_ERROR_CODE {
            get {
                return ResourceManager.GetString("NOT_FOUND_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string NOT_MAPPED_EXCEPTION_ERROR_CODE {
            get {
                return ResourceManager.GetString("NOT_MAPPED_EXCEPTION_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string NOT_MAPPED_EXCEPTION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("NOT_MAPPED_EXCEPTION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string EXTERNAL_API_RETURN_UNSUCCESFULLY_STATUSCODE_CODE {
            get {
                return ResourceManager.GetString("EXTERNAL_API_RETURN_UNSUCCESFULLY_STATUSCODE_CODE", resourceCulture);
            }
        }
        
        public static string EXTERNAL_API_RETURN_UNSUCCESFULLY_STATUSCODE_MESSAGE {
            get {
                return ResourceManager.GetString("EXTERNAL_API_RETURN_UNSUCCESFULLY_STATUSCODE_MESSAGE", resourceCulture);
            }
        }
        
        public static string UNSUPPORTED_API_VERSION_ERROR_CODE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_API_VERSION_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string UNSUPPORTED_API_VERSION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("UNSUPPORTED_API_VERSION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_IS_INVALID_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_IS_INVALID_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_IS_INVALID_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_IS_INVALID_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_IS_LIMITED_TO_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_IS_LIMITED_TO_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_IS_LIMITED_TO_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_IS_LIMITED_TO_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_NOT_EMPTY_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EMPTY_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_NOT_EMPTY_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_EMPTY_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_NOT_NULL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_NULL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_NOT_NULL_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_NOT_NULL_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_GREATER_THEN_OR_EQUAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_GREATER_THEN_OR_EQUAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string VALIDATION_GREATER_THEN_OR_EQUAL_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_GREATER_THEN_OR_EQUAL_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_LESS_THEN_OR_EQUAL_ERROR_CODE {
            get {
                return ResourceManager.GetString("VALIDATION_LESS_THEN_OR_EQUAL_ERROR_CODE", resourceCulture);
            }
        }
        
        public static string VALIDATION_LESS_THEN_OR_EQUAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("VALIDATION_LESS_THEN_OR_EQUAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        public static string LIMIT_PAGE_SIZE {
            get {
                return ResourceManager.GetString("LIMIT_PAGE_SIZE", resourceCulture);
            }
        }
        
        public static string MIN_LIMIT_PAGE_SIZE {
            get {
                return ResourceManager.GetString("MIN_LIMIT_PAGE_SIZE", resourceCulture);
            }
        }
        
        public static string MIN_LIMIT_PAGE_NUMBER {
            get {
                return ResourceManager.GetString("MIN_LIMIT_PAGE_NUMBER", resourceCulture);
            }
        }
    }
}
